export const outliers = [
  "available (item)",
  "available (time)",
  "big (height)",
  "big (thing)",
  "bitter (taste)",
  "brilliant (object)",
  "brilliant (person)",
  "calm (feelings)",
  "general (adj)",
  "left (side)",
  "light (weight)",
  "long (time)",
  "old(age)",
  "present (hazir)",
  "private (adj)",
  "right (correct)",
  "right (side)",
  "second (time)",
  "short (height)",
  "short (time)",
  "small (height)",
  "small (thing)",
  "sour (taste)",
  "sweet (taste)",
  "tall (height)",
  "So (Accentuator)",
  "So (In Order To)",
  "So (Interjection)",
  "TV (Television)",
  "mobile (decoration)",
  "model (art)",
  "scale (art)",
  "ATM (Automated Teller Machine)",
  "bank assurance (Insurance)",
  "NIC (National Identity Card)",
  "pound (currency)",
  "foundation (makeup)",
  "highlights (hair)",
  "chiken (meat)",
  "HP (Hewlett-Packard)",
  "Big King Buns (4 Inch)",
  "Bun Specialty (7 Inch)",
  "Manager Scarf (Ladies)",
  "Heavy Duty Degreaser (K)",
  "Mortein (Insect spray)",
  "one sixth (1/6)",
  "Stainless Steel Polish (K)",
  "foundation (basis)",
  "plaster (white cement)",
  "azure (sky blue)",
  "PC (personal computer)",
  "power supply (computer)",
  "settings (IT)",
  "share (IT)",
  "Windows (IT)",
  "Bachelor of Science (BSc)",
  "aunt (khala)",
  "aunt (paternal-1)",
  "aunt (phuppi)",
  "aunt-in-law (mumani)",
  "aunt-in-law (tai)",
  "aunt-in-law (maternal)",
  "aunt-in-law (paternal)",
  "brother-in-law (sala)",
  "friend (female)",
  "friend (male)",
  "granddaughter (maternal)",
  "grandfather (maternal)",
  "granddaughter (paternal)",
  "grandfather (paternal)",
  "grandmother (maternal)",
  "grandmother (paternal)",
  "grandson (maternal)",
  "grandson (paternal)",
  "great-grandfather (paternal)",
  "great-grandmother (maternal)",
  "great-grandmother (paternal)",
  "great-grandson (maternal)",
  "great-grandfather (maternal)",
  "great-grandson (paternal)",
  "materbal cousin (male)",
  "maternal cousin (female)",
  "nephew (father side)",
  "nephew (maternal)",
  "nephew (mother side)",
  "nephew (paternal)",
  "niece (father side)",
  "niece (maternal)",
  "niece (paternal)",
  "niece (mother side)",
  "sister-in-law (brother's wife)",
  "sister-in-law (maternal)",
  "sister-in-law (husband's sister)",
  "sister-in-law (wife's sister)",
  "sister-in-law (paternal)",
  "son-in-law (daughter's husband)",
  "uncle (maamoo)",
  "uncle (chacha)",
  "babul (acacia nilotica)",
  "bulrush (cattail)",
  "Himalayan butterfly bush (buddleja crispa)",
  "palm (coconut)",
  "palm (date)",
  "tamarisk (salt cedar)",
  "syrup (cake)",
  "syrup (medicine)",
  "ANP (Awami National Party)",
  "NBP (National Bank of Pakistan)",
  "PML (Pakistan Muslim League)",
  "PPP (Pakistan Peoples Party)",
  "PTI (Pakistan Tehreek-e-Insaf)",
  "contraction (grammer)",
  "gift wrap (verb)",
  "Amma Hawa (A.S)",
  "Companion of Prophet Muhammed (PBUH)",
  "companions of Prophet Muhammad (sallallahu alaihi wasallam)",
  "companions of Prophet Muhammad (PBUH)",
  "Hazrat Abu Bakar Siddique (R.A)",
  "Hazrat Abbas (R.A)",
  "Hazrat Abu Huraira (R.A)",
  "Hazrat Aisha (R.A)",
  "Hazrat Ali (R.A)",
  "Hazrat Anus (R.A)",
  "Hazrat Ammar (R.A)",
  "Hazrat Bilal (R.A)",
  "Hazrat Fatima (R.A)",
  "Hazrat Hamza (R.A)",
  "Hazrat Hanzala (R.A)",
  "Hazrat Huzaifa (R.A)",
  "Hazrat Ibn Abbas (R.A)",
  "Hazrat Izrael (A.S)",
  "Hazrat Israfil (A.S)",
  "Hazrat Jibrael (A.S)",
  "Hazrat Khalid Bin Walid (R.A)",
  "Hazrat Khizar (A.S)",
  "Hazrat Musab (R.A)",
  "Hazrat Mikael (A.S)",
  "Hazrat Umar Farooq (R.A)",
  "Hazrat Usman Ghani (R.A)",
  "Hazrat Zakariya (A.S)",
  "Prophet Adam (A.S)",
  "Prophet Ayub (A.S)",
  "Prophet Ibrahim (A.S)",
  "Prophet Dawood (A.S)",
  "Prophet Isa (A.S)",
  "Prophet Ismail (A.S)",
  "Prophet Loot (A.S)",
  "Prophet Moosa (A.S)",
  "Prophet Yousuf (A.S)",
  "Prophet Nooh (A.S)",
  "Prophet Shoaib (A.S)",
  "Prophet Suleman (A.S)",
  "Prophet Yunus (A.S)",
  "fry (verb)",
  "carry (math)",
  "degree (math)",
  "heart (shape)",
  "pound (weight)",
  "scale (weight)",
  "action(media)",
  "Fear of missing out (FOMO)",
  "film (movie)",
  "WWW (world wide web)",
  "organ (music)",
  "answer (noun)",
  "carbohydrates (formula)",
  "Dryer (washing machine)",
  "honour (esteem)",
  "hire (job)",
  "private (company)",
  "Baldia Town (Karachi)",
  "Chandni (saddar)",
  "Charing Cross (Lahore)",
  "Chandni (Saddar,Karachi)",
  "Golimar (Karachi)",
  "Gujranwala (Punjab)",
  "Gulberg (Lahore)",
  "Gulishan-e-Iqbal (Karachi)",
  "Gulistan-e-Jauar (Karachi)",
  "Gulistan-e-Sajjad (Hyderabad)",
  "Hala Naka (Hyderabad)",
  "Hyderi Town (Karachi)",
  "Johar Town (Lahore)",
  "Larkana (Sindh)",
  "Model Town (Lahore)",
  "Pakka Qila (Hyderabad)",
  "Phuleli Canal (Hyderabad)",
  "Queens Road (Sukkur)",
  "Racecourse Park (Lahore)",
  "Rashidabad (Tando Allah Yar)",
  "Rohri (Sindh)",
  "Shalimar Garden (Lahore)",
  "academic (scholar)",
  "announcer (radio/TV)",
  "developer (web/software)",
  "disc jockey (DJ)",
  "marshal (military)",
  "minister (government)",
  "painter(house)",
  "his/hers (feminine)",
  "his/hers (masculine)",
  "DNA (Deoxyribonucleic acid)",
  "solution (chemical)",
  "volume (measurement)",
  "anesthesia of eye (numbness of eye)",
  "Use SMBG (Self-Management Blood Glucose)",
  "iron (verb)",
  "chinese salt (MSG)",
  "fenugreek (meethi)",
  "match (game)",
  "out (cricket)",
  "CMT(Cut, Make,and Trim)",
  "arrange(1)",
  "assemble (gathering)",
  "beat (hit)",
  "bless (give)",
  "delivery (letter)",
  "fill (liquid)",
  "grow (plant)",
  "grow (person)",
  "hire (rent)",
  "hurt (emotion)",
  "leave (chorna)",
  "lie (tell a lie)",
  "lie (down)",
  "play (game)",
  "play (operate)",
  "play (instrument)",
  "release (living things)",
  "sign (signature)",
  "sign (language)",
  "squint (eye deviation)",
  "spend (time)",
  "spend (money)",
  "wash (face)",
  "wash (dishes)",
  "wash (clothes)",
  "patient (hospital)",
  "calm (weather)",
  "cold (weather)",
  "warm (weather)",
];
